#ifndef PIXELDATA_H
#define PIXELDATA_H

#include <stdint.h>

#define COLOR_BLACK 0x0000
#define COLOR_WHITE 0xFFFF
#define COLOR_RED  0x001F
#define COLOR_GREY 0x6b2e
#define COLOR_PURPLE 0x4815
#define COLOR_GREEN 0x26c0
#define COLOR_DARK_ORANGE   0xA800 // Approx. RGB(170, 64, 0)
#define COLOR_MEDIUM_ORANGE 0xFC00 // Approx. RGB(255, 128, 0)
#define COLOR_YELLOW        0xFFE0 // Approx. RGB(255, 252, 0)

#define FONT_START_CHAR  ' '
#define FONT_END_CHAR    'Z'
#define FONT_NUM_CHARS   (FONT_END_CHAR - FONT_START_CHAR + 1)


const uint16_t ship_data[] = {
    COLOR_BLACK,COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_GREY, COLOR_GREY, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, // Row 0
    COLOR_BLACK,COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_GREY, COLOR_GREY, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, // Row 1
    COLOR_BLACK,COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_GREY, COLOR_GREY, COLOR_PURPLE, COLOR_PURPLE, COLOR_GREY, COLOR_GREY, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, // Row 2
    COLOR_BLACK,COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_GREY, COLOR_GREY, COLOR_PURPLE, COLOR_PURPLE, COLOR_GREY, COLOR_GREY, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, // Row 3
    COLOR_BLACK,COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_GREY, COLOR_GREY, COLOR_PURPLE, COLOR_PURPLE, COLOR_GREY, COLOR_GREY, COLOR_PURPLE, COLOR_PURPLE, COLOR_GREY, COLOR_GREY, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK,COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_GREY, COLOR_GREY, COLOR_PURPLE, COLOR_PURPLE, COLOR_GREY, COLOR_GREY, COLOR_PURPLE, COLOR_PURPLE, COLOR_GREY, COLOR_GREY, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_GREY, COLOR_GREY, COLOR_BLACK, COLOR_BLACK, COLOR_GREY, COLOR_GREY, COLOR_PURPLE, COLOR_PURPLE, COLOR_GREY, COLOR_GREY, COLOR_PURPLE, COLOR_PURPLE, COLOR_GREY, COLOR_GREY, COLOR_BLACK, COLOR_BLACK, COLOR_GREY, COLOR_GREY,  // Row 4
    COLOR_GREY, COLOR_GREY, COLOR_BLACK, COLOR_BLACK, COLOR_GREY, COLOR_GREY, COLOR_PURPLE, COLOR_PURPLE, COLOR_GREY, COLOR_GREY, COLOR_PURPLE, COLOR_PURPLE, COLOR_GREY, COLOR_GREY, COLOR_BLACK, COLOR_BLACK, COLOR_GREY, COLOR_GREY, // Row 0
    COLOR_GREY, COLOR_GREY, COLOR_GREY, COLOR_GREY, COLOR_GREY, COLOR_GREY, COLOR_PURPLE, COLOR_PURPLE, COLOR_GREY, COLOR_GREY, COLOR_PURPLE, COLOR_PURPLE, COLOR_GREY, COLOR_GREY, COLOR_GREY, COLOR_GREY, COLOR_GREY, COLOR_GREY, // Row 1
    COLOR_GREY, COLOR_GREY, COLOR_GREY, COLOR_GREY, COLOR_GREY, COLOR_GREY, COLOR_PURPLE, COLOR_PURPLE, COLOR_GREY, COLOR_GREY, COLOR_PURPLE, COLOR_PURPLE, COLOR_GREY, COLOR_GREY, COLOR_GREY, COLOR_GREY, COLOR_GREY, COLOR_GREY, // Row 2
    COLOR_GREY, COLOR_GREY, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_GREY, COLOR_GREY, COLOR_GREY, COLOR_GREY, COLOR_GREY, COLOR_GREY, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_GREY, COLOR_GREY, // Row 3
    COLOR_GREY, COLOR_GREY, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_GREY, COLOR_GREY, COLOR_GREY, COLOR_GREY, COLOR_GREY, COLOR_GREY, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_GREY, COLOR_GREY 
    
};

const uint16_t alien1[] = {
    // Row 0 (from original rows 0-1)
    COLOR_BLACK, COLOR_BLACK, COLOR_GREEN, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_GREEN, COLOR_BLACK,COLOR_BLACK,

    // Row 1 (from original rows 2-3)
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_GREEN, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_GREEN, COLOR_BLACK, COLOR_BLACK,COLOR_BLACK,

    // Row 2 (from original rows 4-5)
    COLOR_BLACK, COLOR_BLACK, COLOR_GREEN, COLOR_GREEN, COLOR_GREEN, COLOR_GREEN, COLOR_GREEN, COLOR_GREEN, COLOR_GREEN, COLOR_BLACK,COLOR_BLACK,

    // Row 3 (from original rows 6-7)
    COLOR_BLACK, COLOR_GREEN, COLOR_GREEN, COLOR_BLACK, COLOR_GREEN, COLOR_GREEN, COLOR_GREEN, COLOR_BLACK, COLOR_GREEN, COLOR_GREEN,COLOR_BLACK,

    // Row 4 (from original rows 8-9)
    COLOR_GREEN, COLOR_BLACK, COLOR_GREEN, COLOR_GREEN, COLOR_GREEN, COLOR_GREEN, COLOR_GREEN, COLOR_GREEN, COLOR_GREEN, COLOR_BLACK,COLOR_GREEN,

    // Row 5 (from original rows 10-11)
   COLOR_GREEN, COLOR_BLACK, COLOR_GREEN, COLOR_GREEN, COLOR_GREEN, COLOR_GREEN, COLOR_GREEN, COLOR_GREEN, COLOR_GREEN, COLOR_BLACK,COLOR_GREEN,

    // Row 6 (from original rows 12-13)
    COLOR_GREEN, COLOR_BLACK, COLOR_GREEN, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_GREEN, COLOR_BLACK,COLOR_GREEN,

    // Row 7 (from original rows 14-15)
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_GREEN, COLOR_GREEN, COLOR_BLACK, COLOR_GREEN, COLOR_GREEN, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
};

const uint16_t alien2[] = {
    // Row 0 (from original rows 0-1)
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,COLOR_BLACK,

    // Row 1 (from original rows 2-3)
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,COLOR_BLACK,

    // Row 2 (from original rows 4-5)
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,COLOR_BLACK,

    // Row 3 (from original rows 6-7)
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,COLOR_BLACK,

    // Row 4 (from original rows 8-9)
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,COLOR_BLACK,

    // Row 5 (from original rows 10-11)
   COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,COLOR_BLACK,

    // Row 6 (from original rows 12-13)
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,COLOR_BLACK,

    // Row 7 (from original rows 14-15)
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
};
// --- Pixel Arrays for Each Button State/Sprite (7x5 pixels) ---

const uint16_t bullet1[] = {
    COLOR_BLACK,   COLOR_BLACK,   COLOR_BLACK,   COLOR_DARK_ORANGE,   COLOR_BLACK,   COLOR_BLACK,   COLOR_BLACK,
    COLOR_BLACK,   COLOR_BLACK,   COLOR_DARK_ORANGE,   COLOR_MEDIUM_ORANGE, COLOR_DARK_ORANGE,   COLOR_BLACK,   COLOR_BLACK,
    COLOR_DARK_ORANGE,   COLOR_MEDIUM_ORANGE, COLOR_YELLOW,        COLOR_YELLOW,        COLOR_YELLOW,        COLOR_MEDIUM_ORANGE, COLOR_DARK_ORANGE,
    COLOR_BLACK,   COLOR_BLACK,   COLOR_DARK_ORANGE,   COLOR_MEDIUM_ORANGE, COLOR_DARK_ORANGE,   COLOR_BLACK,   COLOR_BLACK,
    COLOR_BLACK,   COLOR_BLACK,   COLOR_BLACK,   COLOR_DARK_ORANGE,   COLOR_BLACK,   COLOR_BLACK,   COLOR_BLACK
};

const uint16_t bullet2[] = {
    COLOR_BLACK,   COLOR_BLACK,   COLOR_BLACK,   COLOR_MEDIUM_ORANGE, COLOR_BLACK,   COLOR_BLACK,   COLOR_BLACK,
    COLOR_BLACK,   COLOR_MEDIUM_ORANGE, COLOR_YELLOW,        COLOR_YELLOW,        COLOR_YELLOW,        COLOR_MEDIUM_ORANGE, COLOR_BLACK,
    COLOR_MEDIUM_ORANGE, COLOR_YELLOW,        COLOR_YELLOW,        COLOR_YELLOW,        COLOR_YELLOW,        COLOR_YELLOW,        COLOR_MEDIUM_ORANGE,
    COLOR_BLACK,   COLOR_MEDIUM_ORANGE, COLOR_YELLOW,        COLOR_YELLOW,        COLOR_YELLOW,        COLOR_MEDIUM_ORANGE, COLOR_BLACK,
    COLOR_BLACK,   COLOR_BLACK,   COLOR_BLACK,   COLOR_MEDIUM_ORANGE, COLOR_BLACK,   COLOR_BLACK,   COLOR_BLACK
};

const uint16_t bullet3[] = {
    COLOR_BLACK,   COLOR_BLACK,   COLOR_BLACK,   COLOR_YELLOW,        COLOR_BLACK,   COLOR_BLACK,   COLOR_BLACK,
    COLOR_BLACK,   COLOR_YELLOW,        COLOR_YELLOW,        COLOR_YELLOW,        COLOR_YELLOW,        COLOR_YELLOW,        COLOR_BLACK,
    COLOR_YELLOW,        COLOR_YELLOW,        COLOR_YELLOW,        COLOR_YELLOW,        COLOR_YELLOW,        COLOR_YELLOW,        COLOR_YELLOW,
    COLOR_BLACK,   COLOR_YELLOW,        COLOR_YELLOW,        COLOR_YELLOW,        COLOR_YELLOW,        COLOR_YELLOW,        COLOR_BLACK,
    COLOR_BLACK,   COLOR_BLACK,   COLOR_BLACK,   COLOR_YELLOW,        COLOR_BLACK,   COLOR_BLACK,   COLOR_BLACK
};

const uint16_t bullet4[] = {
    COLOR_BLACK,   COLOR_BLACK,   COLOR_BLACK,   COLOR_YELLOW,        COLOR_BLACK,   COLOR_BLACK,   COLOR_BLACK,
    COLOR_BLACK,   COLOR_YELLOW,        COLOR_YELLOW,        COLOR_YELLOW,        COLOR_YELLOW,        COLOR_YELLOW,        COLOR_BLACK,
    COLOR_YELLOW,        COLOR_YELLOW,        COLOR_YELLOW,        COLOR_YELLOW,        COLOR_YELLOW,        COLOR_YELLOW,        COLOR_YELLOW,
    COLOR_BLACK,   COLOR_YELLOW,        COLOR_YELLOW,        COLOR_YELLOW,        COLOR_YELLOW,        COLOR_YELLOW,        COLOR_BLACK,
    COLOR_BLACK,   COLOR_BLACK,   COLOR_BLACK,   COLOR_YELLOW,        COLOR_BLACK,   COLOR_BLACK,   COLOR_BLACK
};

const uint16_t* bullet_data[] =  {bullet1, bullet2, bullet3, bullet4};
const uint16_t* alien_data[] = {alien1, alien2};
const int ALIEN_WIDTH = 11;
const int ALIEN_HEIGHT = 8;

const int SHIP_WIDTH = 18;
const int SHIP_HEIGHT = 12;

const int BULLET_WIDTH = 7;
const int BULLET_HEIGHT = 5;






#endif